### ISSUE TITLE
Django Upgrade (1.8 to 1.11)

### ISSUE THREAD

**Issue by dongbohu** [greenelab/tribe#28]
According to Django's official doc:
https://www.djangoproject.com/download/#supported-versions
Djanog 1.11.x seems to be a reasonable version to upgrade to for two reasons:
- It is an **LTS** that will be supported **until at least April 2020**
- It is **the last version** that supports **Python 2.7**.

Once Django is upgrade to 1.11, many other Django-related packages should be upgraded too. I am going to use this issue to keep track of the upgrade info of backend packages that depend upon Django.

**Comment by dongbohu** [comment]
Django related:
---------------------
- Django 1.11.16 --> 
- Django-haystack 2.8.1 (latest)
 https://django-haystack.readthedocs.io/en/v2.8.1/installing_search_engines.html) --> 
- elasticsearch 2.x (ES binding on PyPI) --> 
- Elasticsearch 2.X (backend)

- django-allauth?
- django-appconf?
- django-braces?
- django-celery-transactions?
- django-fixtureless?
- django-genes (in house)
- django-oauth-toolkit?
- django-organisms (in house)
- django-taggit?
- django-tastypie?
- django-transaction-hooks?
- django-uuidfield?

**Comment by dongbohu** [comment]
Celery related:
--------------------
- Celery 4.x: the last version that supports Python 2.x
http://docs.celeryproject.org/en/latest/history/whatsnew-4.0.html#django-support

- **celery-haystack** (a sub-project maintained by `django-haystack` team): 
https://github.com/django-haystack/celery-haystack 
(last updated in PyPI in **November 2015**

- Celery dependencies:
http://docs.celeryproject.org/en/stable/faq.html#does-celery-have-many-dependencies
  - kombu (depends on `amqp`)
  - billiard
  - pytz
  - django-celery (seems to be replaced by `django-celery-result` now)
    - https://pypi.org/project/django_celery_results/
    - http://docs.celeryproject.org/en/stable/faq.html?highlight=django-celery-result#what-purpose-does-the-database-tables-created-by-django-celery-results-have

**Comment by dongbohu** [comment]
Other:
---------
- dogslow?
- lxml?
- mock?
- oauthlib?
- psycopg2-binary?
- python-dateutil?
- python-mimeparse?
- python-openid?
- raven?
- requests-oauthlib?
- requests?
- shortuuid?
- six?
- urllib3?
- gunicorn: 19.9.0 (in use now)

**Comment by dongbohu** [comment]
Warning reported by `manage.py`:
-----------------------------------------------
```
WARNING 
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/celery_haystack/utils.py:2:
RemovedInDjango19Warning: 
django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module
```
Warnings reported in .../tribe-gunicorn-stderr*.log:
-----------------
```
WARNING 
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/django/templatetags/future.py:25: 
RemovedInDjango19Warning: 
Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. 
Use the default `url` tag instead.
  RemovedInDjango19Warning)

WARNING 
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/allauth/account/utils.py:38:
RemovedInDjango19Warning: `request.REQUEST` is deprecated, 
use `request.GET` or `request.POST` instead.
  redirect_to = request.REQUEST.get(redirect_field_name)

WARNING 
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py:126: 
RemovedInDjango19Warning: `MergeDict` is deprecated, use `dict.update()` instead.
  self._request = datastructures.MergeDict(self.POST, self.GET)

WARNING 
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/celery_haystack/tasks.py:3: 
RemovedInDjango19Warning: 
The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from django.db.models.loading import get_model

WARNING 
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/allauth/account/views.py:122:
RemovedInDjango19Warning: 
`request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
  redirect_field_value = self.request.REQUEST 

WARNING
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/allauth/account/views.py:196: 
RemovedInDjango19Warning: `request.REQUEST` is deprecated,
 use `request.GET` or `request.POST` instead.
  redirect_field_value = self.request.REQUEST.get(redirect_field_name)
```

Warnings in .../tribe-celery-stderr*.log
-------------------
```
WARNING 
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/celery_haystack/tasks.py:3:
RemovedInDjango19Warning: 
The utilities in django.db.models.loading are deprecated in favor of the new application 
loading system.
  from django.db.models.loading import get_model

WARNING/MainProcess] 
.../.virtualenvs/tribe/local/lib/python2.7/site-packages/celery/apps/worker.py:161: 
CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers the ability to execute 
any command.  It's important to secure your broker from unauthorized access when using 
pckle, so we think that enabling pickle should require a deliberate action and not be the 
default choice.

If you depend on pickle then you should set a setting to disable this warning and to be sure
that everything will continue working when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.

  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

**Comment by dongbohu** [comment]
`django-haystack` 1.X -> 2.X: 
https://django-haystack.readthedocs.io/en/master/searchqueryset_api.html#field-lookups
```
The "content" filter became the new default filter as of Haystack v2.X (the default in 
Haystack v1.X was "exact"). This changed because "exact" caused problems and 
was unintuitive for new people trying to use Haystack. "content" is a much more 
natural usage.

If you had an app built on Haystack v1.X & are upgrading, you’ll need to sanity-check
& possibly change any code that was relying on the default. The solution is just to 
add "__exact" to any “bare” field in a ".filter(...)" clause.
```

**Comment by dongbohu** [comment]
The following packages in `requirements/base.txt` may be removed after we upgrade Django to 1.9+:
- django-transction-hooks: https://django-transaction-hooks.readthedocs.io/en/latest/
- django-uuidfield: https://github.com/dcramer/django-uuidfield/issues/63#issuecomment-213044090
- shortuuid: ?
- defusedxml: ?
- lxml: ?

**Comment by dongbohu** [comment]
According to Celery 3.1 documentation:
http://docs.celeryproject.org/en/3.1/django/first-steps-with-django.html#using-the-django-orm-cache-as-a-result-backend
`django-celery` (aka. **djcelery**) is needed only when we save the celery task results back to Django's backend database. But on Tribe we are only using Celery to update ELasticsearch index. So `django-celery` may not be necessary.

Here are the files that refers to **djcelery** in Tribe requirement packages:
- celery/bin/beat.py
- celery/events/snapshot.py
- celery/loaders/__init__.py
- celery_haystack/tasks.py
- celery_haystack/test_settings.py
- raven/contrib/django/models.py
- raven/contrib/django/celery/models.py

**Comment by dongbohu** [comment]
https://docs.djangoproject.com/en/2.1/releases/1.10/#features-removed-in-1-10
```
Session verification is enabled regardless of whether or not 
'django.contrib.auth.middleware.SessionAuthenticationMiddleware' is in 
'MIDDLEWARE_CLASSES'. 'SessionAuthenticationMiddleware' no longer 
has any purpose and can be removed from 'MIDDLEWARE_CLASSES'.
```

**Comment by dongbohu** [comment]
When Django is upgraded to 1.9+, this error shows up:
```
File "/home/tribe/tribe/versions/models.py", line 29, in <module>
    class FrozenSetField(models.TextField):
  File "/home/tribe/tribe/versions/models.py", line 34, in FrozenSetField
    __metaclass__ = models.SubfieldBase
AttributeError: 'module' object has no attribute 'SubfieldBase'
```
Here is a solution:
https://stackoverflow.com/questions/35166085/how-to-deal-with-subfieldbase-has-been-deprecated-use-field-from-db-value-inst

**Comment by dongbohu** [comment]
Some package version requirements:
- `django-celery 3.2.2` has requirement `celery<4.0,>=3.1.15` 
- `django-fixtureless` has to be 1.5.1 because `Factory` has been removed since 1.6.x.
- `django-tastypie` has to be `0.13.1` to avoid this error:
```
File ".../.virtualenvs/tribe/local/lib/python2.7/site-packages/tastypie/fields.py", 
line 744, in contribute_to_class
    related_field = getattr(self._resource._meta.object_class, self.attribute, None)
TypeError: Error when calling the metaclass bases
    getattr(): attribute name must be string
```

**Comment by dongbohu** [comment]
Installing this patch:
```bash
pip -e git+https://github.com/django-tastypie/django-tastypie@6cb7da757fd28e0541adefd7a7261df452123750#egg=TastyPie
``` 
seems to fix the tastypie issues on Django 1.11.20, but now the following two test cases failed:

```
======================================================================
FAIL: testGOBPQuery (genesets.tests.GenesetUnregisteredTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tribe/tribe/genesets/tests.py", line 267, in testGOBPQuery
    self.assertEqual(len(self.deserialize(resp)['objects']), 1)
AssertionError: 0 != 1

======================================================================
FAIL: testSearchIndexUpdate (genesets.tests.GenesetUnregisteredTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tribe/tribe/genesets/tests.py", line 300, in testSearchIndexUpdate
    self.assertEqual(len(self.deserialize(resp)['objects']), 2)
AssertionError: 0 != 2
```
The reason seems to be because in:
```python
@override_settings(HAYSTACK_CONNECTIONS=TEST_INDEX, CELERY_ALWAYS_EAGER=True,
                   CELERY_EAGER_PROPAGATES_EXCEPTIONS=True)
```
`CELERY_ALWAYS_EAGER=True` is not effective.  

If we add:
```python
call_command('update_index', interactive=False, verbosity=0)
```
in the two failed test cases, they will pass. But why?

**Comment by dongbohu** [comment]
PR #41 and #42 have removed most django-1.7 deprecated features. Once the new `django-tastypie` is released with the bug fix (django-tastypie/django-tastypie#1583), we need to update `base.txt` and figure out how to fix the two failed test cases above.

**Comment by dongbohu** [comment]
Fixed by PR #52.
